SELECT * FROM CARS
WHERE MIN_PRICE between '300' and '600'

SELECT * FROM CARS
WHERE MIN_PRICE IN('300','600')

SELECT * FROM CARS
WHERE MANUFACTURER LIKE '_o%'

SELECT * FROM CARS
WHERE MANUFACTURER LIKE '__w%'
AND PRICE = '800'

SELECT * 
FROM SQL_EMP1
WHERE TEL is NULL;

SELECT * 
FROM SQL_EMP1
WHERE TEL is not NULL;

SELECT HYDROGEN AS 氫離子濃度指數, SERIAL_NUMBER AS 序號, CHLORINE AS 濁度, CHLORINE AS 自由有效餘氯
FROM SQL_TAOYUAN_WATER
WHERE (HYDROGEN = 7.5 OR HYDROGEN = 8)
AND CHLORINE > 0.6
AND PLACE = 'T22';

SELECT HYDROGEN AS 氫離子濃度指數, SERIAL_NUMBER AS 序號, CHLORINE AS 濁度, CHLORINE AS 自由有效餘氯
FROM SQL_TAOYUAN_WATER
WHERE (SERIAL_NUMBER BETWEEN 521 AND 529) OR (
CHLORINE IN (0.76,0.77,0.66)
AND HYDROGEN != 7.8
AND TURBIDITY = 0.6
);

SELECT DISTINCT MANUFACTURER
FROM CARS

SELECT DISTINCT MANUFACTURER, COUNT(*)
FROM CARS
GROUP BY MANUFACTURER

SELECT * 
FROM CARS
ORDER BY PRICE DESC

SELECT * 
FROM CARS
ORDER BY PRICE DESC, MIN_PRICE ASC

SELECT DISTINCT PLACE,HYDROGEN AS 氫離子濃度指數, SERIAL_NUMBER AS 序號, TURBIDITY AS 濁度, CHLORINE AS 自由有效餘氯
FROM SQL_TAOYUAN_WATER
WHERE (SERIAL_NUMBER BETWEEN 521 AND 529) OR (
CHLORINE IN (0.76,0.77,0.66)
AND HYDROGEN != 7.8
AND TURBIDITY = 0.6)
ORDER BY TURBIDITY ASC,SERIAL_NUMBER DESC

SELECT *
FROM SQL_EMP
WHERE EMP_ID IN (SELECT DISTINCT FROM SQL_CUSTOMER);

SELECT ID 
FROM SQL_EMP
UNION 
SELECT ID 
FROM SQL_CUSTOMER;

SELECT PLACE, HYDROGEN AS 氫離子濃度指數, SERIAL_NUMBER AS 序號, CHLORINE AS 濁度, CHLORINE AS 自由有效餘氯
FROM SQL_TAOYUAN_WATER
WHERE (SERIAL_NUMBER BETWEEN 521 AND 529) OR (
CHLORINE IN (0.76,0.77,0.66)
AND HYDROGEN != 7.8
AND TURBIDITY = 0.6)
UNION ALL
SELECT PLACE, HYDROGEN AS 氫離子濃度指數, SERIAL_NUMBER AS 序號, CHLORINE AS 濁度, CHLORINE AS 自由有效餘氯
FROM SQL_TAOYUAN_WATER
WHERE (SERIAL_NUMBER BETWEEN 521 AND 529) OR (
CHLORINE IN (0.76,0.77,0.66)
AND HYDROGEN != 7.8
AND TURBIDITY = 0.6)
--ORDER BY TURBIDITY ASC, SERIAL_NUMBER DESC

SELECT PLACE, HYDROGEN , SERIAL_NUMBER,TURBIDITY,CHLORINE
FROM(
    SELECT PLACE, HYDROGEN, SERIAL_NUMBER, TURBIDITY, CHLORINE
    FROM SQL_TAOYUAN_WATER
    WHERE (SERIAL_NUMBER BETWEEN 521 AND 529)
    UNION 
    SELECT PLACE, HYDROGEN, SERIAL_NUMBER, TURBIDITY, CHLORINE
    FROM SQL_TAOYUAN_WATER
    WHERE CHLORINE IN (0.76,0.77,0.66)
    AND HYDROGEN != 7.8
    AND TURBIDITY = 0.6
)

SELECT PLACE, HYDROGEN, SERIAL_NUMBER, TURBIDITY, CHLORINE
    FROM SQL_TAOYUAN_WATER
    WHERE (SERIAL_NUMBER BETWEEN 521 AND 529)
UNION 
SELECT PLACE, HYDROGEN, SERIAL_NUMBER, TURBIDITY, CHLORINE
    FROM SQL_TAOYUAN_WATER
    WHERE CHLORINE IN (0.76,0.77,0.66)
    AND HYDROGEN != 7.8
    AND TURBIDITY = 0.6
    
SELECT * FROM SQL_CUSTOMER 

SELECT CUT.NAME, EMP.EMP_NM, DEP.ADDR
FROM SQL_CUSTOMER CUT
LEFT JOIN SQL_EMP EMP ON CUT.EMP=EMP.EMP_ID
LEFT JOIN SQL_DEP DEP ON EMP.DEP=DEP.DEP

SELECT  DATA.HYDROGEN , DATA.SERIAL_NUMBER,DATA.TURBIDITY,DATA.CHLORINE,DATA.WATER_SYSTEM,WW.WATER_PURIFICATION_PLANT,WW.WATER_SUPPLY,RR.TOWNSHIP,RR.PLACE
FROM(
    SELECT PLACE, HYDROGEN, SERIAL_NUMBER, TURBIDITY, CHLORINE,WATER_SYSTEM
    FROM SQL_TAOYUAN_WATER
    WHERE (SERIAL_NUMBER BETWEEN 521 AND 529)
    UNION 
    SELECT PLACE, HYDROGEN, SERIAL_NUMBER, TURBIDITY, CHLORINE,WATER_SYSTEM
    FROM SQL_TAOYUAN_WATER
    WHERE CHLORINE IN (0.76,0.77,0.66)
    AND HYDROGEN != 7.8
    AND TURBIDITY = 0.6
)DATA
LEFT JOIN SQL_TAOYUAN_REGIONS RR ON RR.SERIAL = DATA.PLACE
LEFT JOIN SQL_TAOYUAN_WATER_SYSTEM WW ON WW.SERIAL = DATA.WATER_SYSTEM

SELECT DEP, COUNT(ID) AS CNT
FROM SQL_EMP
GROUP BY DEP

SELECT EMP,COUNT(ID) AS CNT
FROM SQL_CUSTOMER
WHERE EMP IS NOT NULL
GROUP BY EMP
HAVING COUNT(ID)>1
ORDER BY CNT DESC,EMP

SELECT DEPARTMENT_ID, COUNT(EMPLOYEE_ID)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID

SELECT DISTINCT EE.DEPARTMENT_ID, DD.DEPARTMENT_NAME, COUNT(EE.DEPARTMENT_ID)
FROM EMPLOYEES EE
LEFT JOIN DEPARTMENTS DD ON EE.DEPARTMENT_ID= DD.DEPARTMENT_ID
GROUP BY EE.DEPARTMENT_ID,DD.DEPARTMENT_NAME

SELECT COUNT(*)CNt
FROM EMPLOYEES
WHERE JOB_ID ='IT_PROG'

SELECT LAST_NAME, SALARY, SALARY+300
FROM EMPLOYEES

SELECT LAST_NAME || ' IS A ' || JOB_ID AS K
FROM EMPLOYEES

SELECT PLACE, COUNT(PLACE)AS 地區總比數, MAX(CHLORINE),MIN(CHLORINE),SUM(HYDROGEN),AVG(TURBIDITY)
FROM SQL_TAOYUAN_WATER
WHERE PLACE IN ('T40','T44','T16')
GROUP BY PLACE

SELECT COUNT(WW.PLACE),AVG(WW.TURBIDITY), RR.TOWNSHIP
FROM SQL_TAOYUAN_WATER WW
LEFT JOIN SQL_TAOYUAN_REGIONS RR ON WW.PLACE = RR.SERIAL
GROUP BY RR.TOWNSHIP
HAVING AVG(TURBIDITY)> 0.7

SELECT COUNT(WW.PLACE),AVG(WW.TURBIDITY), RR.TOWNSHIP
FROM SQL_TAOYUAN_WATER WW
RIGHT JOIN SQL_TAOYUAN_REGIONS RR ON WW.PLACE = RR.SERIAL
GROUP BY RR.TOWNSHIP
HAVING AVG(TURBIDITY)> 0.7

INSERT INTO SQL_EMP_HIS(EMP_NM, DEP,EMP_ID)
VALUES('王小明','系統開發部','00012345')

DROP TABLE SQL_EMP_HIS

CREATE TABLE SQL_EMP_HIS AS SELECT* FROM SQL_EMP

INSERT INTO SQL_EMP_HIS
SELECT EMP_ID, EMP_NM, ID ,NULL,'資訊板塊'
FROM SQL_EMP_HIS
WHERE EMP_ID = '00012345'

UPDATE SQL_EMP_HIS
SET DEP = '資訊板塊'
WHERE EMP_ID = '00054321'

DELETE FROM SQL_EMP_HIS
WHERE DEP = '開發系統部'

INSERT INTO SQL_EMP_HIS(EMP_ID,EMP_NM,ID,TEL,DEP)
VALUES('0056','SEAN','00056789','09375488369','證券部')

UPDATE SQL_EMP_HIS
SET ID = 'P0000000', TEL = '9999#9999'
WHERE EMP_ID = '0056'

DELETE FROM SQL_EMP_HIS
WHERE EMP_ID = '0056'

SELECT LAST_NAME, JOB_ID, SALARY
FROM EMPLOYEES
WHERE JOB_ID = (SELECT JOB_ID 
                FROM EMPLOYEES 
                WHERE EMPLOYEE_ID = '141')
AND
    SALARY > (SELECT SALARY
              FROM EMPLOYEES
              WHERE  EMPLOYEE_ID = '143')
              
SELECT FIRST_NAME, JOB_ID, SALARY
FROM EMPLOYEES
WHERE SALARY = (SELECT MIN(SALARY)
                FROM EMPLOYEES)
                
SELECT DEPARTMENT_ID, MIN(SALARY)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
HAVING MIN(SALARY)> (SELECT  MIN(SALARY)
                     FROM EMPLOYEES
                     WHERE DEPARTMENT_ID = 50)
SELECT EMPLOYEE_ID, LAST_NAME , JOB_ID ,SALARY
FROM EMPLOYEES
WHERE SALARY < ANY
                  (SELECT SALARY
                   FROM EMPLOYEES
                   WHERE JOB_ID = 'IT_PROG')
AND JOB_ID != <> 'IT_PROG'

SELECT EMPLOYEE_ID, LAST_NAME,JOB_ID ,SALARY
FROM EMPLOYEES
WHERE SALARY < ALL
                (SELECT SALARY 
                 FROM EMPLOYEES
                 WHERE JOB_ID = 'IT_PROG')
AND JOB_ID != 'IT_PROG'    

SELECT last_name,
  UPPER(CONCAT(SUBSTR (LAST_NAME, 1, 8), '_US'))
FROM   employees
WHERE  department_id = 60;
