SELECT * FROM CARS
WHERE MIN_PRICE between '300' and '600'

SELECT * FROM CARS
WHERE MIN_PRICE IN('300','600')

SELECT * FROM CARS
WHERE MANUFACTURER LIKE '_o%'

SELECT * FROM CARS
WHERE MANUFACTURER LIKE '__w%'
AND PRICE = '800'

SELECT * 
FROM SQL_EMP1
WHERE TEL is NULL;

SELECT * 
FROM SQL_EMP1
WHERE TEL is not NULL;

SELECT HYDROGEN AS 氫離子濃度指數, SERIAL_NUMBER AS 序號, CHLORINE AS 濁度, CHLORINE AS 自由有效餘氯
FROM SQL_TAOYUAN_WATER
WHERE (HYDROGEN = 7.5 OR HYDROGEN = 8)
AND CHLORINE > 0.6
AND PLACE = 'T22';

SELECT HYDROGEN AS 氫離子濃度指數, SERIAL_NUMBER AS 序號, CHLORINE AS 濁度, CHLORINE AS 自由有效餘氯
FROM SQL_TAOYUAN_WATER
WHERE (SERIAL_NUMBER BETWEEN 521 AND 529) OR (
CHLORINE IN (0.76,0.77,0.66)
AND HYDROGEN != 7.8
AND TURBIDITY = 0.6
);

SELECT DISTINCT MANUFACTURER
FROM CARS

SELECT DISTINCT MANUFACTURER, COUNT(*)
FROM CARS
GROUP BY MANUFACTURER

SELECT * 
FROM CARS
ORDER BY PRICE DESC

SELECT * 
FROM CARS
ORDER BY PRICE DESC, MIN_PRICE ASC

SELECT DISTINCT PLACE,HYDROGEN AS 氫離子濃度指數, SERIAL_NUMBER AS 序號, TURBIDITY AS 濁度, CHLORINE AS 自由有效餘氯
FROM SQL_TAOYUAN_WATER
WHERE (SERIAL_NUMBER BETWEEN 521 AND 529) OR (
CHLORINE IN (0.76,0.77,0.66)
AND HYDROGEN != 7.8
AND TURBIDITY = 0.6)
ORDER BY TURBIDITY ASC,SERIAL_NUMBER DESC

SELECT *
FROM SQL_EMP
WHERE EMP_ID IN (SELECT DISTINCT FROM SQL_CUSTOMER);

SELECT ID 
FROM SQL_EMP
UNION 
SELECT ID 
FROM SQL_CUSTOMER;

SELECT PLACE, HYDROGEN AS 氫離子濃度指數, SERIAL_NUMBER AS 序號, CHLORINE AS 濁度, CHLORINE AS 自由有效餘氯
FROM SQL_TAOYUAN_WATER
WHERE (SERIAL_NUMBER BETWEEN 521 AND 529) OR (
CHLORINE IN (0.76,0.77,0.66)
AND HYDROGEN != 7.8
AND TURBIDITY = 0.6)
UNION ALL
SELECT PLACE, HYDROGEN AS 氫離子濃度指數, SERIAL_NUMBER AS 序號, CHLORINE AS 濁度, CHLORINE AS 自由有效餘氯
FROM SQL_TAOYUAN_WATER
WHERE (SERIAL_NUMBER BETWEEN 521 AND 529) OR (
CHLORINE IN (0.76,0.77,0.66)
AND HYDROGEN != 7.8
AND TURBIDITY = 0.6)
--ORDER BY TURBIDITY ASC, SERIAL_NUMBER DESC

SELECT PLACE, HYDROGEN , SERIAL_NUMBER,TURBIDITY,CHLORINE
FROM(
    SELECT PLACE, HYDROGEN, SERIAL_NUMBER, TURBIDITY, CHLORINE
    FROM SQL_TAOYUAN_WATER
    WHERE (SERIAL_NUMBER BETWEEN 521 AND 529)
    UNION 
    SELECT PLACE, HYDROGEN, SERIAL_NUMBER, TURBIDITY, CHLORINE
    FROM SQL_TAOYUAN_WATER
    WHERE CHLORINE IN (0.76,0.77,0.66)
    AND HYDROGEN != 7.8
    AND TURBIDITY = 0.6
)

SELECT PLACE, HYDROGEN, SERIAL_NUMBER, TURBIDITY, CHLORINE
    FROM SQL_TAOYUAN_WATER
    WHERE (SERIAL_NUMBER BETWEEN 521 AND 529)
UNION 
SELECT PLACE, HYDROGEN, SERIAL_NUMBER, TURBIDITY, CHLORINE
    FROM SQL_TAOYUAN_WATER
    WHERE CHLORINE IN (0.76,0.77,0.66)
    AND HYDROGEN != 7.8
    AND TURBIDITY = 0.6
    
SELECT * FROM SQL_CUSTOMER 

SELECT CUT.NAME, EMP.EMP_NM, DEP.ADDR
FROM SQL_CUSTOMER CUT
LEFT JOIN SQL_EMP EMP ON CUT.EMP=EMP.EMP_ID
LEFT JOIN SQL_DEP DEP ON EMP.DEP=DEP.DEP

SELECT DATA.PLACE, DATA.HYDROGEN , DATA.SERIAL_NUMBER,DATA.TURBIDITY,DATA.CHLORINE,DATA.WATER_SYSTEM,WATER_PURIFICATION_PLANT,WATER_SUPPLY,TOWNSHIP
FROM(
    SELECT PLACE, HYDROGEN, SERIAL_NUMBER, TURBIDITY, CHLORINE,WATER_SYSTEM
    FROM SQL_TAOYUAN_WATER
    WHERE (SERIAL_NUMBER BETWEEN 521 AND 529)
    UNION 
    SELECT PLACE, HYDROGEN, SERIAL_NUMBER, TURBIDITY, CHLORINE,WATER_SYSTEM
    FROM SQL_TAOYUAN_WATER
    WHERE CHLORINE IN (0.76,0.77,0.66)
    AND HYDROGEN != 7.8
    AND TURBIDITY = 0.6
)DATA
LEFT JOIN SQL_TAOYUAN_REGIONS ON SQL_TAOYUAN_REGIONS.SERIAL = DATA.PLACE
LEFT JOIN SQL_TAOYUAN_WATER_SYSTEM ON SQL_TAOYUAN_WATER_SYSTEM.SERIAL = DATA.WATER_SUPPLY
